<?php
/**
*This is simply a reference page containing 1 multi-dimensional array
*Champions array contains 17 sub-arrays: a distinct champion with 11 attributes each
*/
$champions = array(
//ASHE
array(
	'name' => 'Ashe',
	'laning' => "33",		 		 
	'kiting' => "0",		 		
	'support1' => "1",		
	'dodging' => "100",		 		 
	'teamfighting' => "50",		 	 
	'support2' => "2",		
	'positioning' => "25",		 	 
	'dueling' => "33",		 		 
	'landing' => "33",		 		 
	'support3' => "3",		
	),
//CAITLYN
array(
	'name' => 'Caitlyn',
	'laning' => "67",		 		 
	'kiting' => "0",		 		 
	'support1' => "1",		
	'dodging' => "0",		 		 
	'teamfighting' => "25",		 	 
	'support2' => "2",		
	'positioning' => "50",		 	 
	'dueling' => "67",		 		 
	'landing' => "0",		 		 
	'support3' => "3",		
	),
//CORKI
array(
	'name' => 'Corki',
	'laning' => "33",		 		 
	'kiting' => "50",		 		 
	'support1' => "2",		
	'dodging' => "67",		 		 
	'teamfighting' => "25",		 	 
	'support2' => "1",		
	'positioning' => "50",		 	 
	'dueling' => "33",		 		 
	'landing' => "100",		 		 
	'support3' => "2",		
	),
//DRAVEN
array(
	'name' => 'Draven',
	'laning' => "100",		 		 
	'kiting' => "100",		 		 
	'support1' => "2",		
	'dodging' => "100",		 		 
	'teamfighting' => "75",		 	 
	'support2' => "1",		
	'positioning' => "0",		 	 
	'dueling' => "100",		 		 
	'landing' => "33",		 		 
	'support3' => "2",		
	),
//EZREAL
array(
	'name' => 'Ezreal',
	'laning' => "33",		 		 
	'kiting' => "75",		 		 
	'support1' => "2",		
	'dodging' => "67",		 		 
	'teamfighting' => "75",		 	 
	'support2' => "1",		
	'positioning' => "100",		 	 
	'dueling' => "100",		 		 
	'landing' => "67",		 		 
	'support3' => "2",		
	),
//GRAVES
array(
	'name' => 'Graves',
	'laning' => "67",		 		 
	'kiting' => "0",		 		 
	'support1' => "3",		
	'dodging' => "33",		 		 
	'teamfighting' => "0",		 	 
	'support2' => "3",		
	'positioning' => "50",		 	 
	'dueling' => "100",		 		 
	'landing' => "33",		 		 
	'support3' => "1",		
	),
//JHIN
array(
	'name' => 'Jhin',
	'laning'=> "0",			 		 
	'kiting' => "50",		 		 
	'support1' => "2",		
	'dodging' => "67",		 		 
	'teamfighting' => "50",		 	 
	'support2' => "1",		
	'positioning' => "0",		 	 
	'dueling' => "0",		 		 
	'landing' => "100",		 		 
	'support3' => "2",		
	),
//JINX
array(
	'name' => 'Jinx',
	'laning' => "67",		 		 
	'kiting' => "50",		 		 
	'support1' => "2",		
	'dodging' => "100",		 		 
	'teamfighting' => "75",		 	 
	'support2' => "1",		
	'positioning' => "25",		 	 
	'dueling' => "33",		 		 
	'landing' => "67",		 		 
	'support3' => "2",		
	),
//KALISTA
array(
	'name' => 'Kalista',
	'laning' => "0",		 		 
	'kiting' => "100",		 		 
	'support1' => "3",		
	'dodging' => "0",		 		 
	'teamfighting' => "75",		 	 
	'support2' => "3",		
	'positioning' => "100",		 	 
	'dueling' => "75",		 		 
	'landing' => "0",		 		 
	'support3' => "1",		
	),
//KOG MAW
array(
	'name' => 'KogMaw',
	'laning' => "0",		 		 
	'kiting' => "100",		 		 
	'support1' => "1",		
	'dodging' => "100",		 		 
	'teamfighting' => "100",		 	 
	'support2' => "2",		
	'positioning' => "0",		 	 
	'dueling' => "0",		 		 
	'landing' => "67",		 		 
	'support3' => "3",		
	),
//LUCIAN
array(
	'name' => 'Lucian',
	'laning' => "100",		 		 
	'kiting' => "75",		 		 
	'support1' => "3",		
	'dodging' => "33",		 		 
	'teamfighting' => "50",		 	 
	'support2' => "3",		
	'positioning' => "100",		 	 
	'dueling' => "100",		 		 
	'landing' => "0",		 		 
	'support3' => "1",		
	),
//MFORTUNE
array(
	'name' => 'MissFortune',
	'laning' => "67",		 		 
	'kiting' => "25",		 		 
	'support1' => "1",		
	'dodging' => "67",		 		 
	'teamfighting' => "0",		 	 
	'support2' => "2",		
	'positioning' => "25",		 	 
	'dueling' => "0",		 		 
	'landing' => "67",		 		 
	'support3' => "3",		
	),
//SIVIR
array(
	'name' => 'Sivir',
	'laning' => "67",		 		 
	'kiting' => "75",		 		 
	'support1' => "1",		
	'dodging' => "0",		 		 
	'teamfighting' => "0",		 	 
	'support2' => "2",		
	'positioning' => "75",		 	 
	'dueling' => "33",		 		 
	'landing' => "33",		 		 
	'support3' => "3",		
	),
//TRISTANA
array(
	'name' => 'Tristana',
	'laning' => "33",		 		 
	'kiting' => "25",		 		 
	'support1' => "3",		
	'dodging' => "67",		 		 
	'teamfighting' => "100",		 	 
	'support2' => "3",		
	'positioning' => "50",		 	 
	'dueling' => "67",		 		 
	'landing' => "0",		 		 
	'support3' => "1",		
	),
//TWITCH
array(
	'name' => 'Twitch',
	'laning' => "33",		 		 
	'kiting' => "25",		 		 
	'support1' => "2",		
	'dodging' => "67",		 		 
	'teamfighting' => "100",		 	 
	'support2' => "1",		
	'positioning' => "25",		 	 
	'dueling' => "67",		 		 
	'landing' => "33",		 		 
	'support3' => "2",		
	),
//VARUS
array(
	'name' => 'Varus',
	'laning' => "100",		 		 
	'kiting' => "75",		 		 
	'support1' => "2",		
	'dodging' => "100",		 		 
	'teamfighting' => "25",		 	 
	'support2' => "1",		
	'positioning'=> "0",			 	 
	'dueling' => "33",		 		 
	'landing' => "100",		 		 
	'support3' => "2",		
	),
//VAYNE
array(
	'name' => 'Vayne',
	'laning' => "0",		 		 
	'kiting' => "100",		 		 
	'support1' => "3",		
	'dodging' => "33",		 		 
	'teamfighting' => "100",		 	 
	'support2' => "3",		
	'positioning' => "75",		 	 
	'dueling' => "100",		 		 
	'landing' => "0",		 		 
	'support3' => "1",		
	),
);
